name: Code Quality Check

on:
  push:
    branches: [main]
  pull_request:
    branches: ["*"]

jobs:
  code-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - run: flutter pub get

      - run: flutter analyze

      - run: flutter pub run dart_code_metrics:metrics analyze lib

      - run: flutter test
